# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='65656565', help_text='Customer ID associated with the payment gateway', max_length=8, verbose_name='Customer ID'),
            preserve_default=False,
        ),
    ]
