# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 07:30
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current card balance', max_digits=4, verbose_name='Balance')),
                ('child', models.ForeignKey(help_text='Child user of this card', on_delete=django.db.models.deletion.CASCADE, related_name='child_cards', to=settings.AUTH_USER_MODEL, verbose_name='Child')),
                ('parent', models.ForeignKey(help_text='Parent user of this card', on_delete=django.db.models.deletion.CASCADE, related_name='parent_cards', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(b'expense', 'Expense'), (b'top-up', 'Top-up')], default=b'expense', help_text='Type of transaction ("expense" by default)', max_length=10, verbose_name='Type')),
                ('time', models.DateTimeField(auto_now=True, help_text='Time of transaction', verbose_name='Time')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transaction amount', max_digits=3, verbose_name='Amount')),
                ('card', models.ForeignKey(help_text='Card used in this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to='cards.Card', verbose_name='Card')),
                ('user', models.ForeignKey(help_text='User who has made the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
