# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='12345678', help_text='Transaction ID associated with the payment gateway', max_length=8, verbose_name='Transaction ID'),
        ),
    ]
